### PR TITLE
Update Open-Sesame_Mainline.lua to open everything

### PR DESCRIPTION
**Pull request by mergele4**
Updated to open everything that "hasLoot" and isn't locked.

### CODE REVIEW

**Comment by mergele4** [comment]
This basically makes the whitelist extraneous. Anything that has loot and is not locked or doesn't require a higher level than the player will be automatically opened. Tested it for a bit on a few characters and it seems to work as expected.

**Comment by Gogo1951** [comment]
The problem is there are items that have BoP items inside. We don't want to open those, so we need some sort of whitelist.

**Comment by Gogo1951** [comment]
But I do like checking to see if lockboxes are unlocked, and if they are, opening them.

**Comment by Gogo1951** [comment]
There are also items that contain Unique items inside. Another reason for the white list.

**Comment by Gogo1951** [comment]
But hey mate, this is aligned with some notes I made for myself earlier this week. Love to chat if you want to help out!

# Task List

* Separate Data Files

* Inside each file would be a section for each expansion? Gotta think this through.
	Safe to Delete - Consumable Items
	Safe to Delete - Cosmetic Items
	Safe to Delete - Equipment
	Safe to Delete - Quest Items
	Safe to Open
		Maybe instead of a list there is a function to see if something is openable, and unlocked, and if so try and open it.
			But we'd still need an ignore list, for items that have a BoP in them. 
			Maybe there's a way to look in the bag and see if it has a BoP and if so not try and open it.

* It's supposed to announce the welcome message once per sign-in, but it's announcing once per sign-in or zone change. Boo.
	 Open Sesame : WARNING This is a beta build! Use at your own risk. 
	 Open Sesame : Use /magiceraser to clean up your bags by removing completed quest items, low-level consumables you don't need, or the least valuable vendor item. 

* It's supposed to only announce "Paused" when your bags are full, but it's announcing when you zone into a dungeon as well.
	 Open Sesame : Paused until you have at least 4 free bag spaces available. Use /magiceraser to make some more room. 
	 Open Sesame : WARNING This is a beta build! Use at your own risk. 
	 Open Sesame : Use /magiceraser to clean up your bags by removing completed quest items, low-level consumables you don't need, or the least valuable vendor item. 

* Add variable for add-on name so I can change that later.

* Add options interface for which data files to include. 

* Add options interface for what kinds of stuff to delete.
	* grays
	* "trash" whites
	* old quest items for completed quests
	* cheap consumes
	* reagents for other classes
* Add pop-up previewing what would be deleted.
* Show how many things could be deleted.

* Fix consume check so it isn't use-item on all approved delete list.

Logic on Deleting...

	* Check for items associated with quests that have been completed.
	* Check for low-value item to delete.
		* Check the Consumables List for items that have a use-level lower than 10 levels below the player's level
		* Check the Safe to Delete List.
		* Check for gray items.
			(Need a don't delete list. There's one-gray item that starts a quest so maybe we do need a safe list. Fuckers.)

**Comment by Gogo1951** [comment]
Also I just tested your code in Classic Era, and... it's not working right. 

GetItemInfo is not returning the correct item type, so I'm having to go back to the manual ID list anyway. 

Ruh roh!

**Comment by mergele4** [comment]
Hey Gogo, sorry, I don't play Classic so I wasn't able to test there, but it's working fine in retail.

> The problem is there are items that have BoP items inside. We don't want to open those, so we need some sort of whitelist.

Seems like the easiest workaround here would be to only open soulbound containers, or make that an option. Are you aware of any specific edge cases where a tradeable container contains BoP or unique items?

Regarding item deletion and bag cleanup, that feels like it should be a separate addon. Should be simple enough to add a free space check and not auto-open containers if you have less than N free bag slots, though.

**Review by Gogo1951 — COMMENTED** [review]
👍

**Comment by Gogo1951** [comment]
Agreed on separate add-on.

**Pull request merged**
